/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        cream: '#FFF8F0',
        ink: '#1F2933',
        muted: '#4A5560',
        sage: '#DDEBDD',
        amber: '#FFF1D6',
        clay: '#FBE4DF',
        marigold: '#F2A33A',
        primary: '#004349',
        'primary-hover': '#0B484E',
        'primary-container': '#0F5C63',
        'on-primary': '#FFFFFF',
        'on-primary-container': '#91D2DA',
        'primary-fixed': '#ACEEF6',
        'primary-fixed-dim': '#90D1D9',
        secondary: '#A53B26',
        'secondary-hover': '#8B2F1C',
        'secondary-container': '#FE7D62',
        'on-secondary': '#FFFFFF',
        'on-secondary-container': '#711605',
        'secondary-fixed': '#FFDAD3',
        'secondary-fixed-dim': '#FFB4A4',
        tertiary: '#583400',
        'tertiary-container': '#774900',
        'on-tertiary': '#FFFFFF',
        'on-tertiary-container': '#FFBA66',
        'tertiary-fixed': '#FFDDB9',
        'tertiary-fixed-dim': '#FFB963',
        'on-tertiary-fixed': '#2B1700',
        'on-tertiary-fixed-variant': '#663E00',
        surface: '#F7F9FF',
        'surface-bright': '#F7F9FF',
        'surface-dim': '#D1DBE8',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#EDF4FF',
        'surface-container': '#E4EFFD',
        'surface-container-high': '#DFE9F7',
        'surface-container-highest': '#D9E3F1',
        'on-surface': '#121D26',
        'on-surface-variant': '#3F484A',
        outline: '#6F797A',
        'outline-variant': '#BFC8C9',
        'inverse-surface': '#27313C',
        'inverse-on-surface': '#E8F2FF',
        error: '#BA1A1A',
        'error-container': '#FFDAD6',
      },
      fontFamily: {
        sans: [
          'Noto Sans',
          'Noto Sans Devanagari',
          'Noto Sans Telugu',
          'Noto Sans Tamil',
          'Noto Sans Kannada',
          'Noto Sans Malayalam',
          'Noto Sans Bengali',
          'system-ui',
          'sans-serif',
        ],
      },
      borderRadius: {
        '20': '20px',
      },
      minHeight: {
        touch: '48px',
        btn: '56px',
      },
      keyframes: {
        'pulse-subtle': {
          '0%, 100%': { opacity: 1, transform: 'scale(1)' },
          '50%': { opacity: 0.85, transform: 'scale(1.04)' },
        },
      },
      animation: {
        'pulse-subtle': 'pulse-subtle 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
};
